### ISSUE TITLE
GetColumnDataType returns Intergers

### ISSUE THREAD

**Issue by kamperzoid** [ricci69/ultimatemysql#10]
Hi,

I need the correct datatype to autocreate my classes in php automaticly.
So i found the function $db->GetColumnDataType top! but there is a but!

It returns ID's and could not find any reference too the datatypes.

I'm using MariaDB and found an version that you can ask the type

i made new function to test this out and it is returning the datatype by name

`    public function GetColumnDataTypeNew($column, $table = "") {
        $this->ResetError();
        if (is_int($column))
            $column = $this->GetColumnName($column, $table);
        $result = $this->QueryArray("SHOW COLUMNS FROM " . $table . " WHERE Field = '" . $column . "'", MYSQLI_ASSOC);
        if (count($result) == 1) {
            return $result[0]["Type"];
        } else {
            $this->SetError("The specified column or table does not exist, or no data was returned", -1);
            return false;
        }
    }`

Hope this can help to make it better?

**Comment by ricci69** [comment]
There isn't an official list. 
The only informations i have found, are inside the comments of the PHP function: https://www.php.net/manual/en/mysqli-result.fetch-field-direct.php#89117 but are 15 years old.

Your solution is good! I will implement it as a new function called GetColumnDataTypeName

**Comment by ricci69** [comment]
I have commited the fix for this issue.

Take care of 2 things:
1- the new function will be available in future 4.7 version. In the meanwhile you must use the dev version ```composer require composer require ricci69/ultimatemysql dev-master```
2- i have seen that this function too is influenced by the daemon, for example it could returns "int" or "int(11)"
